name: Build and Release Tsunami Simulator

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            extension: ''
            pyinstaller_os: 'Linux'
          - os: windows-latest
            extension: '.exe'
            pyinstaller_os: 'Windows'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile simulator/main.py
        shell: bash

      - name: Archive executable
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/main dist/main${{ matrix.extension }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tsunami_simulator-${{ matrix.pyinstaller_os }}
          path: dist/main${{ matrix.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: tsunami_simulator-Linux
          path: artifacts/linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: tsunami_simulator-Windows
          path: artifacts/windows

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/linux/main
            artifacts/windows/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
